Update Place schema
goodmeh/goodmeh-backend pull request #32
Opened 2024-09-16 07:18 UTC by YaleChen299

#23

2024-09-16 07:31 UTC, YaleChen299 commented
seed data for dev will be refactored once i make the test seed factory.

2024-09-16 08:49 UTC, zhekaiii requested changes
Just some minor nits!

2024-09-16 08:49 UTC, zhekaiii commented on tests/review_model_test.py
> +        print(reviews)
oops might wanna remove this

2024-09-16 08:49 UTC, zhekaiii commented on app/models.py
> +    updated_at: so.Mapped[datetime] = so.mapped_column(TZDateTime)
Maybe we can put a default here too?
```py
from sqlalchemy import func
```
and then
```suggestion
    updated_at: so.Mapped[datetime] = so.mapped_column(TZDateTime, default=func.now(), onupdate=func.now())
```
Then we don't have to put updated_at anywhere

2024-09-17 08:31 UTC, zhekaiii approved these changes
LGTM, thanks for the hard work! :)

2024-09-17 08:31 UTC, merged